#include "vm/vtable.h"

const vtable_t VTABLE_ZERO = {
    .add            = NULL,
    .sub            = NULL,
    .mul            = NULL,
    .div            = NULL,
    .mod            = NULL,
    .neg            = NULL,
    .eq             = NULL,
    .ne             = NULL,
    .lt             = NULL,
    .le             = NULL,
    .gt             = NULL,
    .ge             = NULL,
    .band           = NULL,
    .bor            = NULL,
    .bxor           = NULL,
    .bnot           = NULL,
    .shl            = NULL,
    .shr            = NULL,
    .lnot           = NULL,
    .call           = NULL,
    .dispose        = NULL,
    .clone          = NULL,
    .assign         = NULL,
    .implicit_cast  = NULL,
    .explicit_cast  = NULL,
};
